version: "3.8"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    environment:
     - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=50ms
     - GF_DASHBOARDS_REFRESH_INTERVAL=50ms
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      public_net:
        ipv4_address: 192.168.70.168

networks:
    public_net:
        driver: bridge
        external: true
        name:  oai-cn5g-public-net
volumes:
  grafana-storage: {}
