services:
    mysql:
        container_name: "tt-mysql"
        image: mysql:8.0
        volumes:
            - ./oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ./mysql-healthcheck.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 30
        networks:
            public_net:
                ipv4_address: 192.168.71.131
        dns:
            - 8.8.8.8
            - 8.8.4.4
    oai-amf:
        container_name: "tt-oai-amf"
        image: oaisoftwarealliance/oai-amf:v2.0.0
        environment:
            - TZ=Europe/paris
        volumes:
            - ./mini_nonrf_config.yaml:/openair-amf/etc/config.yaml
        depends_on:
            - mysql
        networks:
            public_net:
                ipv4_address: 192.168.71.132
        dns:
            - 8.8.8.8
            - 8.8.4.4
    oai-smf:
        container_name: "tt-oai-smf"
        image: oaisoftwarealliance/oai-smf:v2.0.0
        environment:
            - TZ=Europe/Paris
        volumes:
            - ./mini_nonrf_config.yaml:/openair-smf/etc/config.yaml
        depends_on:
            - oai-amf
        networks:
            public_net:
                ipv4_address: 192.168.71.133
        dns:
            - 8.8.8.8
            - 8.8.4.4
    oai-upf:
        container_name: "tt-oai-upf"
        image: oaisoftwarealliance/oai-upf:v2.0.0
        environment:
            - TZ=Europe/Paris
        volumes:
            - ./mini_nonrf_config.yaml:/openair-upf/etc/config.yaml
        depends_on:
            - oai-smf
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.71.134
            traffic_net:
                ipv4_address: 192.168.72.134
    oai-ext-dn:
        privileged: true
        container_name: tt-oai-ext-dn
        image: oaisoftwarealliance/trf-gen-cn5g:focal
        entrypoint: /bin/bash -c \
              "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
              "ip route add 12.1.1.0/24 via 192.168.72.134 dev eth0; sleep infinity"
        depends_on:
            - oai-upf
        networks:
            traffic_net:
                ipv4_address: 192.168.72.135
        healthcheck:
            test: /bin/bash -c "ping -c 2 192.168.72.134"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-gnb:
        image: my-oai-gnb-image
        #my-oai-gnb-image
        # oaisoftwarealliance/oai-gnb:develop
        container_name: tt-oai-gnb
        cap_drop:
            - ALL
        volumes:
            - ../../targets/PROJECTS/GENERIC-NR-5GC/CONF/gnb.sa.band78.fr1.106PRB.usrpb210.conf:/opt/oai-gnb/etc/gnb.conf
            - ../../channel/real_random_10tap.txt:/opt/oai-gnb/etc/channel/real_random_10tap.txt
            - ../../logs_gnb:/opt/oai-gnb/etc/logs
        environment:
            USE_ADDITIONAL_OPTIONS: --rfsim -E --sa --rfsimulator.options chanmod -T 10 -O /opt/oai-gnb/etc/gnb.conf
            ASAN_OPTIONS: detect_leaks=0
        depends_on:
            - oai-ext-dn
        networks:
            public_net:
                ipv4_address: 192.168.71.140
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue:
        image: my-oai-nr-ue-image
        # my-oai-nr-ue-image
        # oaisoftwarealliance/oai-nr-ue:develop
        container_name: tt-oai-nrue1
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
        volumes:
            - ../../ci-scripts/conf_files/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ../../channel/real_random_10tap.txt:/opt/oai-nr-ue/etc/channel/real_random_10tap.txt
            - ../../logs_ue:/opt/oai-nr-ue/etc/logs
        environment:
            USE_ADDITIONAL_OPTIONS: --uicc0.imsi 001010000000001 -T 10 -C 3619200000 -r 106 --numerology 1 --ssb 516 -E --sa --rfsim --rfsimulator.options chanmod -O /opt/oai-nr-ue/etc/nr-ue.conf
        depends_on:
            - oai-gnb
        networks:
            public_net:
                ipv4_address: 192.168.71.150
        devices:
             - /dev/net/tun:/dev/net/tun
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    # oai-nr-ue2:
    #     image: my-oai-nr-ue-image
    #     container_name: rfsim5g-oai-nr-ue2
    #     cap_drop:
    #         - ALL
    #     cap_add:
    #         - NET_ADMIN  # for interface bringup
    #         - NET_RAW    # for ping
    #     environment:
    #         USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 208990100001101 -C 3319680000 --rfsimulator.serveraddr 192.168.71.140 --log_config.global_log_options level,nocolor,time
    #     depends_on:
    #         - oai-gnb
    #     networks:
    #         public_net:
    #             ipv4_address: 192.168.71.151
    #     devices:
    #          - /dev/net/tun:/dev/net/tun
    #     volumes:
    #         - ../../conf_files/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
    #     healthcheck:
    #         test: /bin/bash -c "pgrep nr-uesoftmodem"
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    # oai-nr-ue3:
    #     image: my-oai-nr-ue-image
    #     container_name: rfsim5g-oai-nr-ue3
    #     cap_drop:
    #         - ALL
    #     cap_add:
    #         - NET_ADMIN  # for interface bringup
    #         - NET_RAW    # for ping
    #     environment:
    #         USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 208990100001102 -C 3319680000 --rfsimulator.serveraddr 192.168.71.140 --log_config.global_log_options level,nocolor,time
    #     depends_on:
    #         - oai-gnb
    #     networks:
    #         public_net:
    #             ipv4_address: 192.168.71.152
    #     devices:
    #          - /dev/net/tun:/dev/net/tun
    #     volumes:
    #         - ../../conf_files/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
    #     healthcheck:
    #         test: /bin/bash -c "pgrep nr-uesoftmodem"
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    # oai-nr-ue4:
    #     image: my-oai-nr-ue-image
    #     container_name: rfsim5g-oai-nr-ue4
    #     cap_drop:
    #         - ALL
    #     cap_add:
    #         - NET_ADMIN  # for interface bringup
    #         - NET_RAW    # for ping
    #     environment:
    #         USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 208990100001103 -C 3319680000 --rfsimulator.serveraddr 192.168.71.140 --log_config.global_log_options level,nocolor,time
    #     depends_on:
    #         - oai-gnb
    #     networks:
    #         public_net:
    #             ipv4_address: 192.168.71.153
    #     devices:
    #          - /dev/net/tun:/dev/net/tun
    #     volumes:
    #         - ../../conf_files/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
    #     healthcheck:
    #         test: /bin/bash -c "pgrep nr-uesoftmodem"
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    # oai-nr-ue5:
    #     image: my-oai-nr-ue-image
    #     container_name: rfsim5g-oai-nr-ue5
    #     cap_drop:
    #         - ALL
    #     cap_add:
    #         - NET_ADMIN  # for interface bringup
    #         - NET_RAW    # for ping
    #     environment:
    #         USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 208990100001104 -C 3319680000 --rfsimulator.serveraddr 192.168.71.140 --log_config.global_log_options level,nocolor,time
    #     depends_on:
    #         - oai-gnb
    #     networks:
    #         public_net:
    #             ipv4_address: 192.168.71.154
    #     devices:
    #          - /dev/net/tun:/dev/net/tun
    #     volumes:
    #         - ../../conf_files/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
    #     healthcheck:
    #         test: /bin/bash -c "pgrep nr-uesoftmodem"
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    # oai-nr-ue6:
    #     image: my-oai-nr-ue-image
    #     container_name: rfsim5g-oai-nr-ue6
    #     cap_drop:
    #         - ALL
    #     cap_add:
    #         - NET_ADMIN  # for interface bringup
    #         - NET_RAW    # for ping
    #     environment:
    #         USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 208990100001105 -C 3319680000 --rfsimulator.serveraddr 192.168.71.140 --log_config.global_log_options level,nocolor,time
    #     depends_on:
    #         - oai-gnb
    #     networks:
    #         public_net:
    #             ipv4_address: 192.168.71.155
    #     devices:
    #          - /dev/net/tun:/dev/net/tun
    #     volumes:
    #         - ../../conf_files/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
    #     healthcheck:
    #         test: /bin/bash -c "pgrep nr-uesoftmodem"
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    # oai-nr-ue7:
    #     image: my-oai-nr-ue-image
    #     container_name: rfsim5g-oai-nr-ue7
    #     cap_drop:
    #         - ALL
    #     cap_add:
    #         - NET_ADMIN  # for interface bringup
    #         - NET_RAW    # for ping
    #     environment:
    #         USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 208990100001106 -C 3319680000 --rfsimulator.serveraddr 192.168.71.140 --log_config.global_log_options level,nocolor,time
    #     depends_on:
    #         - oai-gnb
    #     networks:
    #         public_net:
    #             ipv4_address: 192.168.71.156
    #     devices:
    #          - /dev/net/tun:/dev/net/tun
    #     volumes:
    #         - ../../conf_files/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
    #     healthcheck:
    #         test: /bin/bash -c "pgrep nr-uesoftmodem"
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    # oai-nr-ue8:
    #     image: my-oai-nr-ue-image
    #     container_name: rfsim5g-oai-nr-ue8
    #     cap_drop:
    #         - ALL
    #     cap_add:
    #         - NET_ADMIN  # for interface bringup
    #         - NET_RAW    # for ping
    #     environment:
    #         USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 208990100001107 -C 3319680000 --rfsimulator.serveraddr 192.168.71.140 --log_config.global_log_options level,nocolor,time
    #     depends_on:
    #         - oai-gnb
    #     networks:
    #         public_net:
    #             ipv4_address: 192.168.71.157
    #     devices:
    #          - /dev/net/tun:/dev/net/tun
    #     volumes:
    #         - ../../conf_files/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
    #     healthcheck:
    #         test: /bin/bash -c "pgrep nr-uesoftmodem"
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    # oai-nr-ue9:
    #     image: my-oai-nr-ue-image
    #     container_name: rfsim5g-oai-nr-ue9
    #     cap_drop:
    #         - ALL
    #     cap_add:
    #         - NET_ADMIN  # for interface bringup
    #         - NET_RAW    # for ping
    #     environment:
    #         USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 208990100001108 -C 3319680000 --rfsimulator.serveraddr 192.168.71.140 --log_config.global_log_options level,nocolor,time
    #     depends_on:
    #         - oai-gnb
    #     networks:
    #         public_net:
    #             ipv4_address: 192.168.71.158
    #     devices:
    #          - /dev/net/tun:/dev/net/tun
    #     volumes:
    #         - ../../conf_files/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
    #     healthcheck:
    #         test: /bin/bash -c "pgrep nr-uesoftmodem"
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    # oai-nr-ue10:
    #     image: my-oai-nr-ue-image
    #     container_name: rfsim5g-oai-nr-ue10
    #     cap_drop:
    #         - ALL
    #     cap_add:
    #         - NET_ADMIN  # for interface bringup
    #         - NET_RAW    # for ping
    #     environment:
    #         USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 208990100001109 -C 3319680000 --rfsimulator.serveraddr 192.168.71.140 --log_config.global_log_options level,nocolor,time
    #     depends_on:
    #         - oai-gnb
    #     networks:
    #         public_net:
    #             ipv4_address: 192.168.71.159
    #     devices:
    #          - /dev/net/tun:/dev/net/tun
    #     volumes:
    #         - ../../conf_files/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
    #     healthcheck:
    #         test: /bin/bash -c "pgrep nr-uesoftmodem"
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
networks:
    public_net:
        driver: bridge
        name: tinytwin-oai-public-net
        ipam:
            config:
                - subnet: 192.168.71.128/26
        driver_opts:
            com.docker.network.bridge.name: "tt-public"
    traffic_net:
        driver: bridge
        name: tinytwin-oai-traffic-net
        ipam:
            config:
                - subnet: 192.168.72.128/26
        driver_opts:
            com.docker.network.bridge.name: "tt-traffic"
